# Generated by Django 5.2.9 on 2026-03-02 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnderTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='rbac_teacher_idx'), models.Index(fields=['student'], name='rbac_student_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'student'), name='rbac_unique_teacher_student'), models.CheckConstraint(condition=models.Q(('teacher', models.F('student')), _negated=True), name='rbac_teacher_student_not_same')],
            },
        ),
    ]
