# Generated by Django 5.2.9 on 2026-03-02 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_institution_links', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='rbac_ti_teacher_idx'), models.Index(fields=['institution'], name='rbac_ti_inst_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'institution'), name='rbac_teacher_institution_uq'), models.CheckConstraint(condition=models.Q(('teacher', models.F('institution')), _negated=True), name='rbac_teacher_institution_chk')],
            },
        ),
    ]
