# Generated by Django 5.2.9 on 2026-03-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teachersubjectanswerkey_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpdfupload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_pdf_uploads', to='core.teacher'),
        ),
    ]
