# Generated by Django 5.2.9 on 2026-03-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teachersubjectanswerkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpdfupload',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to='core.student'),
        ),
        migrations.AddField(
            model_name='teacherpdfupload',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_pdf_uploads', to='core.subject'),
        ),
    ]
