# Generated by Django 5.2.9 on 2026-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teacherpdfupload_student_teacherpdfupload_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpdfupload',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teachersubjectanswerkey',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
