# Generated by Django 5.2.9 on 2026-03-07 11:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teacherpdfupload_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpdfupload',
            name='extracted_text_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models._safe_student_text_upload_path),
        ),
        migrations.AddField(
            model_name='teachersubjectanswerkey',
            name='extracted_text_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models._safe_teacher_text_upload_path),
        ),
    ]
